GET http://localhost:3000/

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "nome": "Victhor 4",
    "email": "victhor4@email.com",
    "password": "abc1234"
}

###
DELETE http://localhost:3000/user/8662acc9-a5c5-4424-8e94-8c258b01bc37


###
GET http://localhost:3000/user/drop